[[headers]]
  for="/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000"
    Content-Security-Policy = '''
      default-src 'self';
      img-src * blob: data:;
      script-src 'self' https://cdn.chriszuber.com;
      style-src 'self' 'unsafe-inline' https://cdn.chriszuber.com https://www.youtube.com;
      connect-src 'self' https://api.chriszuber.com https://cdn.chriszuber.com;
      font-src 'self' https://cdn.chriszuber.com;
      media-src *;
      child-src 'self' https://api.chriszuber.com  https://www.youtube.com https://www.youtube-nocookie.com;
      frame-src 'self'  https://www.youtube.com https://www.youtube-nocookie.com;
      worker-src 'self' https://cdn.chriszuber.com;
      block-all-mixed-content;
      upgrade-insecure-requests;
      disown-opener;
      reflected-xss block;
      manifest-src 'self';'''
# [[redirects]]
  # from = ""
  # to = ""
